APP_CPP = spmm.cpp 
APP_HDR = spmm.h
RUN_CPP = Run.cpp

GBENCH := /home/mb2054/scratch/fiddich/gbench/install
RUN_CFLAGS := -I$(GBENCH)/include
RUN_LDFLAGS := -L$(GBENCH)/lib -lbenchmark -pthread

include ../polite.mk