.PHONY: clean All

All:
	@echo "----------Building project:[ matmult-single - Debug ]----------"
	@"$(MAKE)" -f  "matmult-single.mk"
clean:
	@echo "----------Cleaning project:[ matmult-single - Debug ]----------"
	@"$(MAKE)" -f  "matmult-single.mk" clean
