# TCL File Generated by Component Editor 19.2
# Wed Nov 24 14:14:37 GMT 2021
# DO NOT MODIFY


# 
# Tinsel "Tinsel" v1.0
#  2021.11.24.14:14:37
# 
# 

# 
# request TCL package from ACDS 19.4
# 
package require -exact qsys 19.4


# 
# module Tinsel
# 
set_module_property DESCRIPTION ""
set_module_property NAME Tinsel
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME Tinsel
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL de5Top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file de5Top.v VERILOG PATH ../rtl/de5Top.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""
set_interface_property clock IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port clock CLK clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""
set_interface_property reset_sink IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port reset_sink RST_N reset_n Input 1


# 
# connection point dram_master_0
# 
add_interface dram_master_0 avalon start
set_interface_property dram_master_0 addressGroup 0
set_interface_property dram_master_0 addressUnits WORDS
set_interface_property dram_master_0 associatedClock clock
set_interface_property dram_master_0 associatedReset reset_sink
set_interface_property dram_master_0 bitsPerSymbol 8
set_interface_property dram_master_0 burstOnBurstBoundariesOnly false
set_interface_property dram_master_0 burstcountUnits WORDS
set_interface_property dram_master_0 doStreamReads false
set_interface_property dram_master_0 doStreamWrites false
set_interface_property dram_master_0 holdTime 0
set_interface_property dram_master_0 linewrapBursts false
set_interface_property dram_master_0 maximumPendingReadTransactions 0
set_interface_property dram_master_0 maximumPendingWriteTransactions 0
set_interface_property dram_master_0 minimumResponseLatency 1
set_interface_property dram_master_0 readLatency 0
set_interface_property dram_master_0 readWaitTime 1
set_interface_property dram_master_0 setupTime 0
set_interface_property dram_master_0 timingUnits Cycles
set_interface_property dram_master_0 waitrequestAllowance 0
set_interface_property dram_master_0 writeWaitTime 0
set_interface_property dram_master_0 ENABLED true
set_interface_property dram_master_0 EXPORT_OF ""
set_interface_property dram_master_0 PORT_NAME_MAP ""
set_interface_property dram_master_0 CMSIS_SVD_VARIABLES ""
set_interface_property dram_master_0 SVD_ADDRESS_GROUP ""
set_interface_property dram_master_0 IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port dram_master_0 dramIfcs_0_m_readdata readdata Input 256
add_interface_port dram_master_0 dramIfcs_0_m_readdatavalid readdatavalid Input 1
add_interface_port dram_master_0 dramIfcs_0_m_waitrequest waitrequest Input 1
add_interface_port dram_master_0 dramIfcs_0_m_writedata writedata Output 256
add_interface_port dram_master_0 dramIfcs_0_m_address address Output 27
add_interface_port dram_master_0 dramIfcs_0_m_read read Output 1
add_interface_port dram_master_0 dramIfcs_0_m_write write Output 1
add_interface_port dram_master_0 dramIfcs_0_m_burstcount burstcount Output 3


# 
# connection point dram_master_1
# 
add_interface dram_master_1 avalon start
set_interface_property dram_master_1 addressGroup 0
set_interface_property dram_master_1 addressUnits WORDS
set_interface_property dram_master_1 associatedClock clock
set_interface_property dram_master_1 associatedReset reset_sink
set_interface_property dram_master_1 bitsPerSymbol 8
set_interface_property dram_master_1 burstOnBurstBoundariesOnly false
set_interface_property dram_master_1 burstcountUnits WORDS
set_interface_property dram_master_1 doStreamReads false
set_interface_property dram_master_1 doStreamWrites false
set_interface_property dram_master_1 holdTime 0
set_interface_property dram_master_1 linewrapBursts false
set_interface_property dram_master_1 maximumPendingReadTransactions 0
set_interface_property dram_master_1 maximumPendingWriteTransactions 0
set_interface_property dram_master_1 minimumResponseLatency 1
set_interface_property dram_master_1 readLatency 0
set_interface_property dram_master_1 readWaitTime 1
set_interface_property dram_master_1 setupTime 0
set_interface_property dram_master_1 timingUnits Cycles
set_interface_property dram_master_1 waitrequestAllowance 0
set_interface_property dram_master_1 writeWaitTime 0
set_interface_property dram_master_1 ENABLED true
set_interface_property dram_master_1 EXPORT_OF ""
set_interface_property dram_master_1 PORT_NAME_MAP ""
set_interface_property dram_master_1 CMSIS_SVD_VARIABLES ""
set_interface_property dram_master_1 SVD_ADDRESS_GROUP ""
set_interface_property dram_master_1 IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port dram_master_1 dramIfcs_1_m_readdata readdata Input 256
add_interface_port dram_master_1 dramIfcs_1_m_readdatavalid readdatavalid Input 1
add_interface_port dram_master_1 dramIfcs_1_m_waitrequest waitrequest Input 1
add_interface_port dram_master_1 dramIfcs_1_m_writedata writedata Output 256
add_interface_port dram_master_1 dramIfcs_1_m_address address Output 27
add_interface_port dram_master_1 dramIfcs_1_m_read read Output 1
add_interface_port dram_master_1 dramIfcs_1_m_write write Output 1
add_interface_port dram_master_1 dramIfcs_1_m_burstcount burstcount Output 3


# 
# connection point boardid
# 
add_interface boardid conduit end
set_interface_property boardid associatedClock clock
set_interface_property boardid associatedReset ""
set_interface_property boardid ENABLED true
set_interface_property boardid EXPORT_OF ""
set_interface_property boardid PORT_NAME_MAP ""
set_interface_property boardid CMSIS_SVD_VARIABLES ""
set_interface_property boardid SVD_ADDRESS_GROUP ""
set_interface_property boardid IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port boardid setBoardId_id val Input 4


# 
# connection point temperature
# 
add_interface temperature conduit end
set_interface_property temperature associatedClock clock
set_interface_property temperature associatedReset ""
set_interface_property temperature ENABLED true
set_interface_property temperature EXPORT_OF ""
set_interface_property temperature PORT_NAME_MAP ""
set_interface_property temperature CMSIS_SVD_VARIABLES ""
set_interface_property temperature SVD_ADDRESS_GROUP ""
set_interface_property temperature IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port temperature setTemperature_temp val Input 8


# 
# connection point jtag_master
# 
add_interface jtag_master avalon start
set_interface_property jtag_master addressGroup 0
set_interface_property jtag_master addressUnits SYMBOLS
set_interface_property jtag_master associatedClock clock
set_interface_property jtag_master associatedReset reset_sink
set_interface_property jtag_master bitsPerSymbol 8
set_interface_property jtag_master burstOnBurstBoundariesOnly false
set_interface_property jtag_master burstcountUnits WORDS
set_interface_property jtag_master doStreamReads false
set_interface_property jtag_master doStreamWrites false
set_interface_property jtag_master holdTime 0
set_interface_property jtag_master linewrapBursts false
set_interface_property jtag_master maximumPendingReadTransactions 0
set_interface_property jtag_master maximumPendingWriteTransactions 0
set_interface_property jtag_master minimumResponseLatency 1
set_interface_property jtag_master readLatency 0
set_interface_property jtag_master readWaitTime 1
set_interface_property jtag_master setupTime 0
set_interface_property jtag_master timingUnits Cycles
set_interface_property jtag_master waitrequestAllowance 0
set_interface_property jtag_master writeWaitTime 0
set_interface_property jtag_master ENABLED true
set_interface_property jtag_master EXPORT_OF ""
set_interface_property jtag_master PORT_NAME_MAP ""
set_interface_property jtag_master CMSIS_SVD_VARIABLES ""
set_interface_property jtag_master SVD_ADDRESS_GROUP ""
set_interface_property jtag_master IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port jtag_master jtagIfc_uart_address address Output 3
add_interface_port jtag_master jtagIfc_uart_writedata writedata Output 32
add_interface_port jtag_master jtagIfc_uart_write write Output 1
add_interface_port jtag_master jtagIfc_uart_read read Output 1
add_interface_port jtag_master jtagIfc_uart_uart_waitrequest waitrequest Input 1
add_interface_port jtag_master jtagIfc_uart_uart_readdata readdata Input 32

