#ifndef _CONFIG_H_
#define _CONFIG_H_
#define TinselFPDivLatency 24
#define TinselCoresPerFPU 4
#define TinselLogLinesPerMem 26
#define TinselFetcherLogBeatBufferSize 5
#define TinselWordsPerSRAMBeat 0
#define TinselLogBytesPerDRAM 30
#define TinselLogCoresPerBoard 4
#define TinselWordsPerBeat 8
#define TinselLogReliableLinkRecvBufferSize 9
#define TinselLogDRAMsPerBoard 2
#define TinselLogTransmitBufferLen 2
#define TinselFPConvertLatency 6
#define TinselInstrsPerCore 2048
#define TinselMeshXBits1 2
#define TinselMeshXBitsWithinBox 1
#define TinselBytesPerDRAM 1073741824
#define TinselFPCompareLatency 3
#define TinselFPAddSubLatency 14
#define TinselLogBytesPerFlit 4
#define TinselLogFetcherFlitBufferSize 5
#define TinselLogEastWestLinks 0
#define TinselNumEastWestLinks 1
#define TinselBytesPerSRAMBeat 0
#define TinselMailboxMeshXLen 2
#define TinselLinkTimeout 1024
#define TinselLogMaxFlitsPerMsg 2
#define TinselLogWordsPerMailbox 13
#define TinselIntMultLatency 3
#define TinselLogBytesPerMsg 6
#define TinselLogFlitsPerMailbox 11
#define TinselDCacheLogNumWays 4
#define TinselLogNorthSouthLinks 0
#define TinselDCachesPerDRAM 2
#define TinselFPUsPerBoard 4
#define TinselMeshXLenWithinBox 1
#define TinselLogThreadsPerDRAM 6
#define TinselMailboxMeshYBits 1
#define TinselFetcherLogFlitBufferSize 5
#define TinselLogThreadsPerMailbox 6
#define TinselLogLinesPerDRAM 25
#define TinselMeshYBits 1
#define TinselLogWordsPerMsg 4
#define TinselLogCoresPerFPU 2
#define TinselSRAMLatency 8
#define TinselLogBeatsPerDRAM 25
#define TinselMeshYBits1 2
#define TinselWordsPerFlit 4
#define TinselDRAMBase 512
#define TinselDeviceFamily '"Stratix 10"'
#define TinselUseCustomAccelerator false
#define TinselBitsPerFlit 128
#define TinselMeshYLenWithinBox 1
#define TinselBoxMeshXLen 1
#define TinselFetcherLogMsgsPerFlitBuffer 3
#define TinselBoxMesh {{"asdex"}}
#define TinselMaxFlitsPerMsg 4
#define TinselBeatWidth 256
#define TinselLogCoresPerMailbox 2
#define TinselLogOffChipRAMBaseAddr 16
#define TinselBeatsPerLine 1
#define TinselPOLiteDRAMGlobalsLength 16384
#define TinselSharedInstrMem true
#define TinselWordsPerLine 8
#define TinselLogBytesPerDRAMPartition 23
#define TinselNumNorthSouthLinks 1
#define TinselFetcherMsgsPerFlitBuffer 8
#define TinselBytesPerBeat 32
#define TinselMaxBootImageBytes 1024
#define TinselLogCoresPerDCache 1
#define TinselThreadsPerCore 16
#define TinselBitsPerLine 256
#define TinselThreadsPerBoard 256
#define TinselLogBytesPerMailbox 15
#define TinselFPUOpMaxLatency 24
#define TinselProgRouterMaxBurst 4
#define TinselMacLatency 100
#define TinselSRAMStoreLatency 2
#define TinselLogBeatsPerLine 0
#define TinselLogFPUsPerBoard 2
#define TinselPOLiteProgRouterBase 16896
#define TinselBoxMeshYLen 1
#define TinselMaxThreads 1024
#define TinselDCacheSetsPerThread 4
#define TinselLogRoutingEntryLen 5
#define TinselSRAMBurstWidth 3
#define TinselLogThreadsPerCore 4
#define TinselMailboxMeshYLen 2
#define TinselFPMultLatency 11
#define TinselDRAMLatency 20
#define TinselLogThreadsPerBoard 8
#define TinselBoardsPerBox 1
#define TinselBeatBurstWidth 3
#define TinselLogInstrsPerCore 11
#define TinselDCacheNumWays 16
#define TinselDCacheLogSetsPerThread 2
#define TinselLogDCachesPerDRAM 1
#define TinselMailboxesPerBoard 4
#define TinselLogWordsPerFlit 2
#define TinselLogTransmitBufferSize 10
#define TinselDRAMLogMaxInFlight 5
#define TinselMeshYBitsWithinBox 1
#define TinselLogCoresPerBoard1 5
#define TinselEnablePerfCount true
#define TinselTransmitBound 20
#define TinselDRAMsPerBoard 4
#define TinselThreadsPerDRAM 64
#define TinselLogMulticastBufferSize 9
#define TinselLogBytesPerLine 5
#define TinselCoresPerBoard 16
#define TinselLogMailboxesPerBoard 2
#define TinselSRAMsPerBoard None
#define TinselLogBytesPerBeat 5
#define TinselFetcherLogIndQueueSize 1
#define TinselSRAMAddrWidth 12
#define TinselLogWordsPerBeat 3
#define TinselThreadsPerMailbox 64
#define TinselLogMsgsPerMailbox 9
#define TinselFetchersPerProgRouter 6
#define TinselPOLiteProgRouterLength 536854016
#define TinselSRAMLogMaxInFlight 5
#define TinselStratix10 true
#define TinselLogMacRecvBufferSize 5
#define TinselLogWordsPerLine 3
#define TinselLogBeatsPerMem 26
#define TinselLogBytesPerMem 31
#define TinselMailboxMeshXBits 1
#define TinselCoresPerMailbox 4
#define TinselClockFreq 200
#define TinselSRAMDataWidth 0
#define TinselLogBytesPerSRAMBeat 3
#define TinselLogMsgPtrQueueSize 6
#define TinselDRAMGlobalsLength 536870400
#define TinselCoresPerDCache 2
#define TinselMeshXBits 1
#define TinselLogThreadsPerFPU 6
#endif
