#ifndef _CONFIG_H_
#define _CONFIG_H_
#define TinselDeviceFamily '"Stratix 10"'
#define TinselLogThreadsPerCore 4
#define TinselLogInstrsPerCore 11
#define TinselSharedInstrMem true
#define TinselLogCoresPerDCache 2
#define TinselLogDCachesPerDRAM 2
#define TinselLogWordsPerBeat 3
#define TinselLogBeatsPerLine 1
#define TinselDCacheLogSetsPerThread 2
#define TinselDCacheLogNumWays 4
#define TinselLogDRAMsPerBoard 2
#define TinselSRAMsPerBoard None
#define TinselDRAMLogMaxInFlight 5
#define TinselDRAMLatency 20
#define TinselLogBeatsPerDRAM 25
#define TinselLogWordsPerFlit 2
#define TinselLogMaxFlitsPerMsg 2
#define TinselLogMsgsPerMailbox 9
#define TinselLogCoresPerMailbox 2
#define TinselMailboxMeshXBits 2
#define TinselMailboxMeshYBits 2
#define TinselLogMsgPtrQueueSize 6
#define TinselLogMulticastBufferSize 9
#define TinselMaxBootImageBytes 1024
#define TinselLogTransmitBufferSize 10
#define TinselLogMacRecvBufferSize 5
#define TinselLogReliableLinkRecvBufferSize 9
#define TinselTransmitBound 20
#define TinselLinkTimeout 1024
#define TinselMacLatency 100
#define TinselMeshXBits 1
#define TinselMeshXBits1 2
#define TinselMeshYBits 1
#define TinselMeshYBits1 2
#define TinselMeshXBitsWithinBox 1
#define TinselMeshYBitsWithinBox 1
#define TinselMeshXLenWithinBox 1
#define TinselMeshYLenWithinBox 1
#define TinselLogCoresPerFPU 0
#define TinselLogNorthSouthLinks 0
#define TinselLogEastWestLinks 0
#define TinselIntMultLatency 3
#define TinselFPMultLatency 11
#define TinselFPAddSubLatency 14
#define TinselFPDivLatency 24
#define TinselFPConvertLatency 6
#define TinselFPCompareLatency 3
#define TinselSRAMAddrWidth 12
#define TinselLogBytesPerSRAMBeat 3
#define TinselSRAMBurstWidth 3
#define TinselSRAMLatency 8
#define TinselSRAMLogMaxInFlight 5
#define TinselSRAMStoreLatency 2
#define TinselLogRoutingEntryLen 5
#define TinselProgRouterMaxBurst 4
#define TinselFetcherLogIndQueueSize 1
#define TinselFetcherLogBeatBufferSize 5
#define TinselFetcherLogFlitBufferSize 5
#define TinselFetcherLogMsgsPerFlitBuffer 3
#define TinselFetcherMsgsPerFlitBuffer 8
#define TinselEnablePerfCount true
#define TinselBoxMeshXLen 1
#define TinselBoxMeshYLen 1
#define TinselBoxMesh {{"asdex"}}
#define TinselUseCustomAccelerator false
#define TinselClockFreq 200
#define TinselStratix10 true
#define TinselLogMailboxesPerBoard 4
#define TinselMailboxMeshXLen 4
#define TinselMailboxMeshYLen 4
#define TinselInstrsPerCore 2048
#define TinselDCacheSetsPerThread 4
#define TinselDCacheNumWays 16
#define TinselLogWordsPerLine 4
#define TinselLogBytesPerLine 6
#define TinselWordsPerLine 16
#define TinselBitsPerLine 512
#define TinselBeatsPerLine 2
#define TinselWordsPerBeat 8
#define TinselBytesPerBeat 32
#define TinselBytesPerDRAM 1073741824
#define TinselLogBytesPerBeat 5
#define TinselBeatWidth 256
#define TinselBeatBurstWidth 3
#define TinselCoresPerDCache 4
#define TinselDCachesPerDRAM 4
#define TinselMaxFlitsPerMsg 4
#define TinselLogFlitsPerMailbox 11
#define TinselLogWordsPerMailbox 13
#define TinselLogBytesPerMailbox 15
#define TinselWordsPerFlit 4
#define TinselLogBytesPerFlit 4
#define TinselBitsPerFlit 128
#define TinselLogWordsPerMsg 4
#define TinselLogBytesPerMsg 6
#define TinselCoresPerMailbox 4
#define TinselLogThreadsPerMailbox 6
#define TinselThreadsPerMailbox 64
#define TinselLogOffChipRAMBaseAddr 16
#define TinselLogTransmitBufferLen 2
#define TinselMailboxesPerBoard 16
#define TinselDRAMsPerBoard 4
#define TinselLogLinesPerDRAM 24
#define TinselLogBytesPerDRAM 30
#define TinselLogThreadsPerDRAM 8
#define TinselThreadsPerDRAM 256
#define TinselLogBytesPerDRAMPartition 17
#define TinselLogThreadsPerBoard 10
#define TinselThreadsPerBoard 1024
#define TinselLogCoresPerBoard 6
#define TinselLogCoresPerBoard1 7
#define TinselCoresPerBoard 64
#define TinselThreadsPerCore 16
#define TinselMaxThreads 4096
#define TinselLogBeatsPerMem 25
#define TinselLogBytesPerMem 30
#define TinselLogLinesPerMem 24
#define TinselCoresPerFPU 1
#define TinselLogThreadsPerFPU 4
#define TinselLogFPUsPerBoard 6
#define TinselFPUsPerBoard 64
#define TinselFPUOpMaxLatency 24
#define TinselNumNorthSouthLinks 1
#define TinselNumEastWestLinks 1
#define TinselBytesPerSRAMBeat 0
#define TinselWordsPerSRAMBeat 0
#define TinselSRAMDataWidth 0
#define TinselDRAMBase 512
#define TinselDRAMGlobalsLength 536870400
#define TinselPOLiteDRAMGlobalsLength 16384
#define TinselPOLiteProgRouterBase 16896
#define TinselPOLiteProgRouterLength 536854016
#define TinselBoardsPerBox 1
#define TinselFetchersPerProgRouter 8
#define TinselLogFetcherFlitBufferSize 5
#endif
